# Generated by Django 5.2.5 on 2025-08-31 09:12

from django.db import migrations


def create_initial_genres(apps, schema_editor):
    Genre = apps.get_model("movie", "Genre")
    initial_genres = ["Action", "Comedy", "Drama", "Horror", "Sci-Fi", "Romance"]
    for name in initial_genres:
        Genre.objects.create(name=name)


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_genres, migrations.RunPython.noop),
    ]
