# Generated by Django 5.2.5 on 2025-08-31 11:19

from django.db import migrations
from django_celery_beat.models import IntervalSchedule, PeriodicTask


def create_daily_task(apps, schema_editor):
    schedule, created = IntervalSchedule.objects.get_or_create(
        every=1, period=IntervalSchedule.DAYS
    )
    PeriodicTask.objects.create(
        interval=schedule,
        name="Send daily movie email",
        task="user.tasks.send_daily_email",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_daily_task, migrations.RunPython.noop)]
